services:
  # Web service
  - type: web
    name: emailer-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: emailer-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0

  # Worker service for processing email tasks
  - type: worker
    name: emailer-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: rq worker email_tasks
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: emailer-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0

  # Redis service
  - type: redis
    name: emailer-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere